export const meals = [
  {
    id: 1,
    name: "Smoked Beef",
    ingredientIds: [24, 2, 23],
    imgSrc: "/steak.jpg",
    preparationTime: "30 - 40 minutes",
    description: "with Bacon, Old Bay Fries, Caramelized Onion & Special Sauce",
    price: 340,
    tags: ["main", "nonfasting"],
  },
  {
    id: 2,
    name: "Cheese Burger",
    ingredientIds: [3, 5, 4, 1],
    imgSrc: "/cheeseburger.jpg",
    preparationTime: "20 - 30 minutes",
    description: "Classic burger with melted cheese.",
    price: 280,
    tags: ["main", "nonfasting"],
  },
  {
    id: 3,
    name: "Chicken Alfredo",
    ingredientIds: [3, 7, 5],
    imgSrc: "/chickenalfredo.jpg",
    preparationTime: "25 - 35 minutes",
    description: "Creamy pasta with grilled chicken.",
    price: 320,
    tags: ["main", "nonfasting"],
  },
  {
    id: 4,
    name: "Veggie Pizza",
    ingredientIds: [7, 1, 5, 4],
    imgSrc: "/veggiepizza.jpg",
    preparationTime: "30 - 40 minutes",
    description: "Loaded with fresh vegetables.",
    price: 250,
    tags: ["main", "fasting"],
  },
  {
    id: 5,
    name: "Grilled Salmon",
    ingredientIds: [10, 14],
    imgSrc: "/grilledsalmon.jpg",
    preparationTime: "20 - 25 minutes",
    description: "Perfectly grilled salmon with lemon.",
    price: 450,
    tags: ["main", "nonfasting"],
  },
  {
    id: 6,
    name: "Pasta Primavera",
    ingredientIds: [7, 14, 8],
    imgSrc: "/pastaprimavera.jpg",
    preparationTime: "30 minutes",
    description: "Fresh pasta with seasonal vegetables.",
    price: 280,
    tags: ["main", "fasting"],
  },
  {
    id: 7,
    name: "Beef Tacos",
    ingredientIds: [3, 1, 12, 8],
    imgSrc: "/beeftacos.jpg",
    preparationTime: "15 - 20 minutes",
    description: "Spicy beef tacos with fresh toppings.",
    price: 220,
    tags: ["main", "nonfasting"],
  },
  {
    id: 8,
    name: "Shrimp Fried Rice",
    ingredientIds: [9, 8, 14],
    imgSrc: "/shrimpfriedrice.jpg",
    preparationTime: "25 - 30 minutes",
    description: "Flavorful shrimp with fried rice.",
    price: 300,
    tags: ["main", "nonfasting"],
  },
  {
    id: 9,
    name: "Chicken Caesar Salad",
    ingredientIds: [3, 4, 1],
    imgSrc: "/chickencaesarsalad.jpg",
    preparationTime: "15 - 20 minutes",
    description: "Classic salad with grilled chicken.",
    price: 260,
    tags: ["main", "fasting"],
  },
  {
    id: 10,
    name: "Spaghetti Carbonara",
    ingredientIds: [7, 6, 5],
    imgSrc: "/spaghetticarbonara.jpg",
    preparationTime: "20 - 25 minutes",
    description: "Rich and creamy spaghetti dish.",
    price: 300,
    tags: ["main", "nonfasting"],
  },
  {
    id: 11,
    name: "Fish and Chips",
    ingredientIds: [10, 11],
    imgSrc: "/fishandchips.jpg",
    preparationTime: "30 - 35 minutes",
    description: "Crispy fish with golden fries.",
    price: 400,
    tags: ["main", "fasting"],
  },
  {
    id: 12,
    name: "Mushroom Risotto",
    ingredientIds: [14, 8, 5],
    imgSrc: "/mushroomrisotto.jpg",
    preparationTime: "30 - 40 minutes",
    description: "Creamy risotto with mushrooms.",
    price: 350,
    tags: ["main", "fasting"],
  },
  {
    id: 13,
    name: "Lamb Chops",
    ingredientIds: [12, 14],
    imgSrc: "/lambchops.jpg",
    preparationTime: "25 - 30 minutes",
    description: "Juicy lamb chops with herbs.",
    price: 500,
    tags: ["main", "nonfasting"],
  },
  {
    id: 14,
    name: "Falafel Wrap",
    ingredientIds: [14, 4, 1],
    imgSrc: "/falafelwrap.jpeg",
    preparationTime: "15 - 20 minutes",
    description: "Healthy wrap with falafel.",
    price: 210,
    tags: ["main", "nonfasting"],
  },
  {
    id: 15,
    name: "Quinoa Bowl",
    ingredientIds: [14, 8],
    imgSrc: "/quinoabowl.jpg",
    preparationTime: "20 - 25 minutes",
    description: "Nutritious quinoa bowl with veggies.",
    price: 250,
    tags: ["main", "fasting"],
  },
  {
    id: 16,
    name: "Chocolate Cake",
    ingredientIds: [15, 16, 17, 18],
    imgSrc: "/chocolatecake.jpg",
    preparationTime: "45 minutes",
    description: "Rich and moist chocolate cake.",
    price: 180,
    tags: ["dessert", "nonfasting"],
  },
  {
    id: 17,
    name: "Fruit Salad",
    ingredientIds: [13],
    imgSrc: "/fruitsalad.jpg",
    preparationTime: "10 minutes",
    description: "Fresh fruit salad with honey.",
    price: 150,
    tags: ["dessert", "fasting"],
  },
  {
    id: 18,
    name: "Tiramisu",
    ingredientIds: [19, 20, 21],
    imgSrc: "/tiramisu.jpg",
    preparationTime: "60 minutes",
    description: "Classic Italian dessert with coffee flavor.",
    price: 220,
    tags: ["dessert", "nonfasting"],
  },
  {
    id: 19,
    name: "Dinich Wot",
    ingredientIds: [11, 2, 22],
    imgSrc: "/dinichwet.jpg",
    preparationTime: "45 minutes",
    description: "Ethiopian potato stew with berbere spice.",
    price: 200,
    tags: ["Ethiopian", "spicy", "main", "fasting"],
  },
  {
    id: 20,
    name: "Doro Wot",
    ingredientIds: [3, 2, 22, 23],
    imgSrc: "/dorowet.png",
    preparationTime: "60 minutes",
    description: "Spicy Ethiopian chicken stew.",
    price: 350,
    tags: ["Ethiopian", "spicy", "main", "nonfasting"],
  },
  {
    id: 21,
    name: "Siga Wot",
    ingredientIds: [24, 2, 22, 23],
    imgSrc: "/sigawet.jpg",
    preparationTime: "60 minutes",
    description: "Spicy Ethiopian beef stew.",
    price: 400,
    tags: ["Ethiopian", "spicy", "main", "nonfasting"],
  },
  {
    id: 22,
    name: "Kitfo",
    ingredientIds: [24, 25, 23],
    imgSrc: "/kitfo.jpg",
    preparationTime: "30 minutes",
    description: "Ethiopian seasoned raw beef.",
    price: 300,
    tags: ["Ethiopian", "spicy", "main", "nonfasting"],
  },
  {
    id: 23,
    name: "Tibs",
    ingredientIds: [24, 2, 23],
    imgSrc: "/tibs.jpg",
    preparationTime: "30 minutes",
    description: "Ethiopian sautéed meat with spices.",
    price: 280,
    tags: ["Ethiopian", "spicy", "main", "nonfasting"],
  },
];



export const ingredients = [
  {
    id: 1,
    name: "Tomatoes",
    price: 40,
    imgSrc: "/tomatoes.jpg",
  },
  {
    id: 2,
    name: "Onions",
    price: 30,
    imgSrc: "/onion.jpg",
  },
  {
    id: 3,
    name: "Chicken",
    price: 100,
    imgSrc: "/chicken.jpg",
  },
  {
    id: 4,
    name: "Lettuce",
    price: 20,
    imgSrc: "/lettuce.jpg",
  },
  {
    id: 5,
    name: "Cheese",
    price: 60,
    imgSrc: "/cheese.jpg",
  },
  {
    id: 6,
    name: "Bacon",
    price: 80,
    imgSrc: "/bacon.jpg",
  },
  {
    id: 7,
    name: "Pasta",
    price: 50,
    imgSrc: "/pasta.jpg",
  },
  {
    id: 8,
    name: "Rice",
    price: 40,
    imgSrc: "/rice.jpg",
  },
  {
    id: 9,
    name: "Shrimp",
    price: 120,
    imgSrc: "/shrimp.jpg",
  },
  {
    id: 10,
    name: "Fish",
    price: 90,
    imgSrc: "/fish.jpg",
  },
  {
    id: 11,
    name: "Potatoes",
    price: 30,
    imgSrc: "/potatoes.jpg",
  },
  {
    id: 12,
    name: "Garlic",
    price: 10,
    imgSrc: "/garlic.jpg",
  },
  {
    id: 13,
    name: "Fruits",
    price: 50,
    imgSrc: "/fruits.jpg",
  },
  {
    id: 14,
    name: "Herbs",
    price: 25,
    imgSrc: "/herbs.jpg",
  },
  {
    id: 15,
    name: "Chocolate",
    price: 50,
    imgSrc: "/chocolate.jpeg",
  },
  {
    id: 16,
    name: "Flour",
    price: 20,
    imgSrc: "/flour.jpg",
  },
  {
    id: 17,
    name: "Sugar",
    price: 10,
    imgSrc: "/suger.jpg",
  },
  {
    id: 18,
    name: "Eggs",
    price: 30,
    imgSrc: "/eggs.jpg",
  },
  {
    id: 19,
    name: "Coffee",
    price: 60,
    imgSrc: "/coffee.jpg",
  },
  {
    id: 20,
    name: "Mascarpone",
    price: 80,
    imgSrc: "/mascarpone.jpg",
  },
  {
    id: 21,
    name: "Ladyfingers",
    price: 40,
    imgSrc: "/ladyfingers.jpg",
  },
  {
    id: 22,
    name: "Berbere", 
    price: 50,
    imgSrc: "/berbere.jpg",
  },
  {
    id: 23,
    name: "Spices", 
    price: 30,
    imgSrc: "/spices.jpg",
  },
  {
    id: 24,
    name: "Meat", 
    price: 120,
    imgSrc: "/meat.jpg",
  },
  {
    id: 25,
    name: "Butter", 
    price: 40,
    imgSrc: "/butter.jpg",
  },
];

