export const meals = [
  {
    id: 1,
    name: "Smoked Beef",
    ingredients: "Meat, Chicken, Onion, Spices",
    imgSrc: "https://source.unsplash.com/400x300/?smoked-beef",
    preparationTime: "30 - 40 minutes",
    description: "Tender smoked beef with rich spices.",
    price: 340,
  },
  {
    id: 2,
    name: "Cheese Burger",
    ingredients: "Beef, Cheese, Lettuce, Tomato, Bun",
    imgSrc: "https://source.unsplash.com/400x300/?cheeseburger",
    preparationTime: "20 - 30 minutes",
    description: "Classic burger with melted cheese.",
    price: 280,
  },
  {
    id: 3,
    name: "Chicken Alfredo",
    ingredients: "Chicken, Pasta, Cream, Parmesan",
    imgSrc: "https://source.unsplash.com/400x300/?chicken-alfredo",
    preparationTime: "25 - 35 minutes",
    description: "Creamy pasta with grilled chicken.",
    price: 320,
  },
  {
    id: 4,
    name: "Veggie Pizza",
    ingredients: "Dough, Tomato Sauce, Cheese, Vegetables",
    imgSrc: "https://source.unsplash.com/400x300/?veggie-pizza",
    preparationTime: "30 - 40 minutes",
    description: "Loaded with fresh vegetables.",
    price: 250,
  },
  {
    id: 5,
    name: "Grilled Salmon",
    ingredients: "Salmon, Lemon, Herbs",
    imgSrc: "https://source.unsplash.com/400x300/?grilled-salmon",
    preparationTime: "20 - 25 minutes",
    description: "Perfectly grilled salmon with lemon.",
    price: 450,
  },
  {
    id: 6,
    name: "Pasta Primavera",
    ingredients: "Pasta, Seasonal Vegetables, Olive Oil",
    imgSrc: "https://source.unsplash.com/400x300/?pasta-primavera",
    preparationTime: "30 minutes",
    description: "Fresh pasta with seasonal vegetables.",
    price: 280,
  },
  {
    id: 7,
    name: "Beef Tacos",
    ingredients: "Beef, Tortillas, Lettuce, Salsa",
    imgSrc: "https://source.unsplash.com/400x300/?beef-tacos",
    preparationTime: "15 - 20 minutes",
    description: "Spicy beef tacos with fresh toppings.",
    price: 220,
  },
  {
    id: 8,
    name: "Shrimp Fried Rice",
    ingredients: "Shrimp, Rice, Vegetables, Soy Sauce",
    imgSrc: "https://source.unsplash.com/400x300/?shrimp-fried-rice",
    preparationTime: "25 - 30 minutes",
    description: "Flavorful shrimp with fried rice.",
    price: 300,
  },
  {
    id: 9,
    name: "Chicken Caesar Salad",
    ingredients: "Chicken, Lettuce, Croutons, Caesar Dressing",
    imgSrc: "https://source.unsplash.com/400x300/?caesar-salad",
    preparationTime: "15 - 20 minutes",
    description: "Classic salad with grilled chicken.",
    price: 260,
  },
  {
    id: 10,
    name: "Spaghetti Carbonara",
    ingredients: "Spaghetti, Bacon, Eggs, Parmesan",
    imgSrc: "https://source.unsplash.com/400x300/?spaghetti-carbonara",
    preparationTime: "20 - 25 minutes",
    description: "Rich and creamy spaghetti dish.",
    price: 300,
  },
  {
    id: 11,
    name: "Fish and Chips",
    ingredients: "Fish, Potatoes, Tartare Sauce",
    imgSrc: "https://source.unsplash.com/400x300/?fish-and-chips",
    preparationTime: "30 - 35 minutes",
    description: "Crispy fish with golden fries.",
    price: 400,
  },
  {
    id: 12,
    name: "Mushroom Risotto",
    ingredients: "Rice, Mushrooms, Broth, Parmesan",
    imgSrc: "https://source.unsplash.com/400x300/?mushroom-risotto",
    preparationTime: "30 - 40 minutes",
    description: "Creamy risotto with mushrooms.",
    price: 350,
  },
  {
    id: 13,
    name: "Lamb Chops",
    ingredients: "Lamb, Herbs, Garlic",
    imgSrc: "https://source.unsplash.com/400x300/?lamb-chops",
    preparationTime: "25 - 30 minutes",
    description: "Juicy lamb chops with herbs.",
    price: 500,
  },
  {
    id: 14,
    name: "Falafel Wrap",
    ingredients: "Falafel, Lettuce, Tomato, Sauce",
    imgSrc: "https://source.unsplash.com/400x300/?falafel-wrap",
    preparationTime: "15 - 20 minutes",
    description: "Healthy wrap with falafel.",
    price: 210,
  },
  {
    id: 15,
    name: "Quinoa Bowl",
    ingredients: "Quinoa, Vegetables, Dressing",
    imgSrc: "https://source.unsplash.com/400x300/?quinoa-bowl",
    preparationTime: "20 - 25 minutes",
    description: "Nutritious quinoa bowl with veggies.",
    price: 250,
  },
  {
    id: 16,
    name: "Chocolate Cake",
    ingredients: "Chocolate, Flour, Sugar, Eggs",
    imgSrc: "https://source.unsplash.com/400x300/?chocolate-cake",
    preparationTime: "45 minutes",
    description: "Rich and moist chocolate cake.",
    price: 180,
  },
  {
    id: 17,
    name: "Fruit Salad",
    ingredients: "Mixed Fruits, Honey",
    imgSrc: "https://source.unsplash.com/400x300/?fruit-salad",
    preparationTime: "10 minutes",
    description: "Fresh fruit salad with honey.",
    price: 150,
  },
  {
    id: 18,
    name: "Tiramisu",
    ingredients: "Coffee, Mascarpone, Ladyfingers",
    imgSrc: "https://source.unsplash.com/400x300/?tiramisu",
    preparationTime: "60 minutes",
    description: "Classic Italian dessert with coffee flavor.",
    price: 220,
  },
];

export const ingredients = [
  {
    id: 1,
    name: "Tomatoes",
    price: 40,
    imgSrc: "https://source.unsplash.com/400x300/?tomatoes",
  },
  {
    id: 2,
    name: "Onions",
    price: 30,
    imgSrc: "https://source.unsplash.com/400x300/?onions",
  },
  {
    id: 3,
    name: "Chicken",
    price: 100,
    imgSrc: "https://source.unsplash.com/400x300/?chicken",
  },
  {
    id: 4,
    name: "Lettuce",
    price: 20,
    imgSrc: "https://source.unsplash.com/400x300/?lettuce",
  },
  {
    id: 5,
    name: "Cheese",
    price: 60,
    imgSrc: "https://source.unsplash.com/400x300/?cheese",
  },
  {
    id: 6,
    name: "Bacon",
    price: 80,
    imgSrc: "https://source.unsplash.com/400x300/?bacon",
  },
  {
    id: 7,
    name: "Pasta",
    price: 50,
    imgSrc: "https://source.unsplash.com/400x300/?pasta",
  },
  {
    id: 8,
    name: "Rice",
    price: 40,
    imgSrc: "https://source.unsplash.com/400x300/?rice",
  },
  {
    id: 9,
    name: "Shrimp",
    price: 120,
    imgSrc: "https://source.unsplash.com/400x300/?shrimp",
  },
  {
    id: 10,
    name: "Fish",
    price: 90,
    imgSrc: "https://source.unsplash.com/400x300/?fish",
  },
  {
    id: 11,
    name: "Potatoes",
    price: 30,
    imgSrc: "https://source.unsplash.com/400x300/?potatoes",
  },
  {
    id: 12,
    name: "Garlic",
    price: 10,
    imgSrc: "https://source.unsplash.com/400x300/?garlic",
  },
  {
    id: 13,
    name: "Fruits",
    price: 50,
    imgSrc: "https://source.unsplash.com/400x300/?fruits",
  },
  {
    id: 14,
    name: "Herbs",
    price: 25,
    imgSrc: "https://source.unsplash.com/400x300/?herbs",
  },]; 


  export { meals, ingredients };
  